apiVersion: v1
kind: Pod
metadata:
  name: ssh-privileged-deployment
  labels:
    app: ssh-privileged
spec:
  nodeName: minikube
  enableServiceLinks: true
  hostIPC: true
  hostNetwork: true
  hostPID: true
  containers:
  - name: ssh-privileged
    image: wooonderful/sshd:v0.2
    securityContext: 
      privileged: true
    ports:
    - containerPort: 2345

---

apiVersion: v1
kind: Service
metadata:
  name: ssh-privileged-svc
spec:
  ports:
  - name: server
    nodePort: 32345
    port: 2345
    targetPort: 2345
  selector:
    app: ssh-privileged
  type: NodePort