apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-deployment
  namespace: emqx-ci-dev
  labels:
    app: sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
      - name: sshd
        image: wooonderful/sshd:v0.2
        ports:
        - containerPort: 22
        - containerPort: 8082


---

apiVersion: v1
kind: Service
metadata:
  name: sshd-svc
  namespace: emqx-ci-dev
spec:
  ports:
  - name: sshd
    port: 22
    protocol: TCP
    targetPort: 22
  - name: server
    port: 8082
    targetPort: 8082
  selector:
    app: sshd
  type: LoadBalancer