apiVersion: apps/v1
kind: Deployment
metadata:
  name: shixiang-sshd-debug
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shixiang-sshd-debug
  template:
    metadata:
      labels:
        app: shixiang-sshd-debug
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/wooon/sshd:0.5
        imagePullPolicy: IfNotPresent
        name: shixiang-sshd-debug
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: shixiang-sshd-debug
  name: shixiang-sshd-debug-svc
spec:
  ports:
  - name: sshd
    nodePort: 30022
    protocol: TCP
    targetPort: 22
    port: 22
  selector:
    app: shixiang-sshd-debug
  type: NodePort
